name: Build and Push Docker Image to GHCR

on:
  push:
    # Trigger the action on any push to the repository
    # This ensures that it runs when changes are made to the Dockerfile or any other files
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract version number from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -oE 'CYBERDROP_VERSION=.+$' Dockerfile | cut -d = -f 2)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV  # Store version in environment variable for later steps

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: rust1v1
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/cyberdrop-dl:${{ env.VERSION }}
          ghcr.io/${{ github.repository_owner }}/cyberdrop-dl:latest
